###
POST http://localhost:3333/usuarios/registrar
Content-Type: application/json

{
    "nome": "John Doe",
    "email": "teste@exemplo.com",
    "senha": "12345678"
}

###
POST http://localhost:3333/usuarios/login
Content-Type: application/json 

{
    "email": "teste@exemplo.com",
    "senha": "12345678"
}

###
GET http://localhost:3333/mesas

###
POST http://localhost:3333/mesas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiM2VmNDA3N2ItYzJlNC00MzdmLWI2ZmYtOGNiNGFiYTU4ODdmIiwibm9tZSI6IkxlYW5kcm8iLCJlbWFpbCI6ImxqMjUxMDA0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzQwNzgxNzEwLCJleHAiOjE3NDA3ODUzMTB9.QDs_eXFZ4IDP4glFmw5vJNF8dX6vA49vi9v2kUchKFE

{
    "nome": "Mesa 1",
    "capacidade": 6,
    "status": "disponivel"
}

###
PATCH http://localhost:3333/mesas/5415e3db-5251-49f4-83a9-7c21bc90785a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiM2VmNDA3N2ItYzJlNC00MzdmLWI2ZmYtOGNiNGFiYTU4ODdmIiwibm9tZSI6IkxlYW5kcm8iLCJlbWFpbCI6ImxqMjUxMDA0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzQwNzgxNzEwLCJleHAiOjE3NDA3ODUzMTB9.QDs_eXFZ4IDP4glFmw5vJNF8dX6vA49vi9v2kUchKFE

{
    "nome": "Mesa 1",
    "capacidade": 6,
    "status": "disponivel"
}

###
DELETE http://localhost:3333/mesas/d0884244-da9c-4125-b14a-60470bdb1c19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiM2VmNDA3N2ItYzJlNC00MzdmLWI2ZmYtOGNiNGFiYTU4ODdmIiwibm9tZSI6IkxlYW5kcm8iLCJlbWFpbCI6ImxqMjUxMDA0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzQwNzgxNzEwLCJleHAiOjE3NDA3ODUzMTB9.QDs_eXFZ4IDP4glFmw5vJNF8dX6vA49vi9v2kUchKFE

###
GET http://localhost:3333/reservas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiM2VmNDA3N2ItYzJlNC00MzdmLWI2ZmYtOGNiNGFiYTU4ODdmIiwibm9tZSI6IkxlYW5kcm8iLCJlbWFpbCI6ImxqMjUxMDA0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzQwNzgxNzEwLCJleHAiOjE3NDA3ODUzMTB9.QDs_eXFZ4IDP4glFmw5vJNF8dX6vA49vi9v2kUchKFE

###
POST http://localhost:3333/reservas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiM2VmNDA3N2ItYzJlNC00MzdmLWI2ZmYtOGNiNGFiYTU4ODdmIiwibm9tZSI6IkxlYW5kcm8iLCJlbWFpbCI6ImxqMjUxMDA0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzQwNzgxNzEwLCJleHAiOjE3NDA3ODUzMTB9.QDs_eXFZ4IDP4glFmw5vJNF8dX6vA49vi9v2kUchKFE

{
    "mesa_id": "c7a38af5-b078-4e06-b5be-09de1db5b49f",
    "data_reserva": "2025-02-28T15:00:00.0Z",
    "capacidade": 6
}

###
PATCH http://localhost:3333/reservas/da8357cc-3082-4c63-8214-fb774c000166/cancelar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiM2VmNDA3N2ItYzJlNC00MzdmLWI2ZmYtOGNiNGFiYTU4ODdmIiwibm9tZSI6IkxlYW5kcm8iLCJlbWFpbCI6ImxqMjUxMDA0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzQwNzgxNzEwLCJleHAiOjE3NDA3ODUzMTB9.QDs_eXFZ4IDP4glFmw5vJNF8dX6vA49vi9v2kUchKFE
